name: Flutter Build CI

on:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: clone repository
              uses: actions/checkout@v4
            - name: Decode Secrets and Create file
              env:
                  GOOGLE_SERVICES_DATA: ${{secrets.GOOGLE_SERVICES_DATA}}
                  FIREBASE_OPTIONS: ${{secrets.FIREBASE_OPTIONS}}
              run: |
                  echo $GOOGLE_SERVICES_DATA | base64 --decode > android/app/google-services.json
                  echo $FIREBASE_OPTIONS | base64 --decode > lib/firebase_options.dart
            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: "3.19.5"
                  channel: "stable"
            - name: Check Flutter Version
              run: flutter --version
            - run: flutter pub get
            - name: Build Android APK
              run: flutter build apk
            - name: Build Android App Bundle
              run: flutter build appbundle
            - name: Upload build apk
              uses: actions/upload-artifact@v4
              with:
                  name: pokemonQuiz.apk
                  path: build/app/outputs/apk/release/app-release.apk
            # macOSで実行する必要があるのでAndroidのビルドだけにする
            # - name: Build iOS
            #   run: flutter build ios --no-codesign
